<?xml version="1.0" encoding="utf-8"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">
  <!-- wheel defining macro -->
  <xacro:macro name="wheel" params="wheel_type wheel_radius prefix">

    <xacro:property name="wheel_separation_x" value="0.106" />
    <xacro:property name="wheel_separation_y" value="0.228" />
    <xacro:property name="wheel_thickness" value="0.036" />

    <xacro:if value="${prefix == 'fl'}">
      <xacro:property name="x" value="${wheel_separation_x/2}" />
      <xacro:property name="y" value="${wheel_separation_y/2 - wheel_thickness/2}" />
      <xacro:property name="y_correction" value="${wheel_thickness/2 - 0.005}" />
      <xacro:property name="rot" value="${pi/2}" />
    </xacro:if>
    <xacro:if value="${prefix == 'fr'}">
      <xacro:property name="x" value="${wheel_separation_x/2}" />
      <xacro:property name="y" value="-${wheel_separation_y/2 - wheel_thickness/2}" />
      <xacro:property name="y_correction" value="-${wheel_thickness/2 - 0.005}" />
      <xacro:property name="rot" value="${-pi/2}" />
    </xacro:if>
    <xacro:if value="${prefix == 'rl'}">
      <xacro:property name="x" value="-${wheel_separation_x/2}" />
      <xacro:property name="y" value="${wheel_separation_y/2 - wheel_thickness/2}" />
      <xacro:property name="y_correction" value="${wheel_thickness/2 - 0.005}" />
      <xacro:property name="rot" value="${pi/2}" />
    </xacro:if>
    <xacro:if value="${prefix == 'rr'}">
      <xacro:property name="x" value="-${wheel_separation_x/2}" />
      <xacro:property name="y" value="-${wheel_separation_y/2 - wheel_thickness/2}" />
      <xacro:property name="y_correction" value="-${wheel_thickness/2 - 0.005}" />
      <xacro:property name="rot" value="${-pi/2}" />
    </xacro:if>

    <joint name="${prefix}_wheel_joint" type="continuous">
      <parent link="body_link" />
      <child link="${prefix}_wheel_link" />
      <origin xyz="${x} ${y} 0.0" rpy="0.0 0.0 0.0" />
      <axis xyz="0.0 1.0 0.0" />
      <limit effort="1.5" velocity="5.0" />
      <dynamics damping="0.001" friction="0.001" />
    </joint>

    <link name="${prefix}_wheel_link">
      <visual>
        <geometry>
          <mesh filename="file://$(find rosbot_description)/meshes/wheel.stl" scale="0.001 0.001 0.001" />
        </geometry>
        <origin xyz="0.0 ${y_correction} 0.0" rpy="0.0 0.0 ${rot}" />
        <material name="Black">
          <color rgba="0.0 0.0 0.0 1.0" />
        </material>
      </visual>

      <collision>
        <geometry>
          <cylinder radius="${wheel_radius}" length="${wheel_thickness}" />
        </geometry>
        <origin xyz="0.0 0.0 0.0" rpy="${pi/2} 0.0 0.0" />
      </collision>

      <inertial>
        <mass value="0.100" />
        <inertia ixx="0.00007" ixy="0.0"       ixz="0.0"
                               iyy="0.0001263" iyz="0.0"
                                               izz="0.00007" />
      </inertial>
    </link>

    <gazebo reference="${prefix}_wheel_link">
      <material>Gazebo/DarkGrey</material>
    </gazebo>

  </xacro:macro>
</robot>